
name: Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Databricks CLI and dependencies
      run: |
        pip install databricks-cli
        pip install urllib3==1.26.6 chardet==3.0.4

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN }}
      run: |
        cat <<EOF | databricks configure --token
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF

    - name: Validate Databricks CLI Configuration
      run: databricks workspace list

    - name: Sync to Databricks
      run: databricks workspace import_dir --overwrite release /Workspace/Users/kalpesh.azure.subscription@gmail.com/dev_release
      
    - name: create delta table directory
      run: |
       mkdir ./delta_tables_dev

    - name: download tables from dev workspace
      run: |
       databricks fs cp --recursive dbfs:/user/hive/warehouse/  ./delta_tables_dev/
       
  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Databricks CLI and dependencies
      run: |
        pip install databricks-cli
        pip install urllib3==1.26.6 chardet==3.0.4

    - name: Configure Databricks CLI
      env:
        PROD_DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}
        PROD_DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}
      run: |
        cat <<EOF | databricks configure --token
        $PROD_DATABRICKS_HOST
        $PROD_DATABRICKS_TOKEN
        EOF

    - name: Validate Databricks CLI Configuration for Production
      run: databricks workspace list

    - name: Sync to Databricks Production
      run: databricks workspace import_dir --overwrite release /Workspace/Users/kalpesh.azure.subscription@gmail.com/prod_release

    - name: upload delta tables to prod
      run: databricks fs cp --recursive ./delta_tables_dev/ dbfs:/dbfs:/user/hive/warehouse/
