
name: Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Databricks CLI and dependencies
      run: |
        pip install databricks-cli
        pip install urllib3==1.26.6 chardet==3.0.4

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN }}
      run: |
        cat <<EOF | databricks configure --token
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF

    - name: Validate Databricks CLI Configuration
      run: databricks workspace list

    - name: Create Delta Table Directory
      run: mkdir -p ./delta_tables_dev

    - name: Verify Delta Table Directory Creation
      run: ls -l

    - name: Download Tables from Dev Workspace
      run: databricks fs cp --recursive dbfs:/user/hive/warehouse/ ./delta_tables_dev/

    - name: Verify Delta Table Download
      run: ls -l ./delta_tables_dev/

    - name: Upload Delta Tables Dev Artifact
      uses: actions/upload-artifact@v3
      with:
        name: delta-tables-dev
        path: ./delta_tables_dev/

    - name: Export Delta Tables from Dev
      run: |
          mkdir -p exported_tables
          databricks fs cp -r dbfs:/FileStore/tables/ exported_tables/
          
  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Databricks CLI and dependencies
      run: |
        pip install databricks-cli
        pip install urllib3==1.26.6 chardet==3.0.4

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}
      run: |
        cat <<EOF | databricks configure --token
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF

    - name: Validate Databricks CLI Configuration for Production
      run: databricks workspace list

    - name: Download Delta Tables Dev Artifact
      uses: actions/download-artifact@v3
      with:
        name: delta-tables-dev
        path: ./delta_tables_dev

    - name: Verify Delta Table Directory after Download
      run: ls -l

    - name: Verify Contents of Delta Table Directory after Download
      run: ls -l ./delta_tables_dev/

    - name: Upload Delta Tables to Prod
      run: databricks fs cp --recursive ./delta_tables_dev/ dbfs:/user/hive/warehouse/

    - name: Upload Delta Tables to Prod
      run: |
          databricks fs cp -r exported_tables/ dbfs:/FileStore/tables/

 	
